r"""Metric counting.

```bash
python3 -m bigquery_etl.glam.bucket_counts
```
"""
from argparse import ArgumentParser
from jinja2 import Environment, PackageLoader

from bigquery_etl.format_sql.formatter import reformat


def render_query(**kwargs) -> str:
    """Render the main query."""
    env = Environment(loader=PackageLoader("bigquery_etl", "glam/templates"))
    sql = env.get_template("clients_scalar_bucket_counts_v1.sql")
    return reformat(sql.render(**kwargs))


def glean_variables():
    """Variables for bucket_counts."""
    attributes_list = ["ping_type", "os", "app_version", "app_build_id", "channel"]
    return dict(
        attributes=",".join(attributes_list),
        # does _not_ include boolean
        scalar_metric_types="""
            "counter",
            "quantity",
            "labeled_counter"
        """,
        boolean_metric_types="""
            "boolean"
        """,
        aggregate_attributes="""
            metric,
            metric_type,
            key
        """,
        aggregate_attributes_type="""
            metric STRING,
            metric_type STRING,
            key STRING
        """,
    )


def main():
    """Generate query for bucketing."""
    parser = ArgumentParser(description=main.__doc__)
    parser.add_argument(
        "--source-table",
        default="glam_etl.fenix_clients_scalar_aggregates_v1",
        help="source table for scalar_bucket_counts",
    )
    args = parser.parse_args()
    module_name = "bigquery_etl.glam.bucket_counts"
    header = f"-- generated by: python3 -m {module_name}"
    header += " " + " ".join([f"--{k} {v}" for k, v in vars(args).items()])
    print(
        render_query(header=header, source_table=args.source_table, **glean_variables())
    )


if __name__ == "__main__":
    main()
